services:
  - type: web
    name: expert-listing
    runtime: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app ./cmd/api
    startCommand: ./app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: APP_ENV
        value: production
